# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 19:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('active', models.BooleanField(default=True, verbose_name='is active')),
                ('user_id', models.CharField(max_length=16, unique=True, verbose_name='enrollment ID')),
                ('date_registered', models.DateTimeField(auto_now_add=True, verbose_name='date registered')),
                ('full_name', models.CharField(max_length=1024, verbose_name='full name')),
                ('email_primary', models.EmailField(max_length=255, unique=True, verbose_name='primary email address')),
                ('email_secondary', models.EmailField(blank=True, max_length=255, null=True, verbose_name='secondary (backup) email address')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='is active')),
                ('name', models.CharField(max_length=128, verbose_name='program name')),
            ],
            options={
                'verbose_name': 'academic program',
                'verbose_name_plural': 'academic programs',
            },
        ),
        migrations.CreateModel(
            name='Dependency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='is active')),
            ],
            options={
                'verbose_name': 'dependency',
                'verbose_name_plural': 'dependencies',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='is active')),
                ('name', models.CharField(max_length=64, verbose_name='role name')),
                ('description', models.CharField(default='', max_length=512, verbose_name='role description')),
                ('_permissions', models.ManyToManyField(related_name='roles', related_query_name='role', to='auth.Permission', verbose_name='permissions')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rhea.Role', verbose_name='parent role')),
            ],
            options={
                'verbose_name': 'user role',
                'verbose_name_plural': 'user roles',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='is active')),
                ('code', models.SlugField(max_length=8, verbose_name='subject code')),
                ('name', models.CharField(max_length=256, verbose_name='subject name')),
                ('dependencies', models.ManyToManyField(related_name='dependents', related_query_name='deps', through='rhea.Dependency', to='rhea.Subject', verbose_name='dependencies')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_subjects', to='rhea.Curriculum', verbose_name='academic program')),
            ],
            options={
                'verbose_name': 'subject',
                'verbose_name_plural': 'subjects',
            },
        ),
        migrations.AddField(
            model_name='dependency',
            name='dependency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_dependents', to='rhea.Subject', verbose_name='dependency'),
        ),
        migrations.AddField(
            model_name='dependency',
            name='dependent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_dependencies', to='rhea.Subject', verbose_name='dependent'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='rhea.Role', verbose_name='user role'),
        ),
    ]
