# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhea', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='semester',
            field=models.PositiveSmallIntegerField(default=0, help_text='\n\t\t\tThe minimum semester in which this course should be taken. Courses that deviate from the\n\t\t\tcurrent semester for a specific student by more than 1 unit upwards are note eligible as\n\t\t\tcandidates for next semester topics.\n\t\t', verbose_name='minimum semester'),
            preserve_default=False,
        ),
    ]
