# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 20:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rhea', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='availability',
            table='a_entry',
        ),
        migrations.AlterModelTable(
            name='availabilityschedule',
            table='a_schedule',
        ),
    ]
