# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 20:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rhea', '0002_auto_20160324_2025'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='availability',
            table='rhea_a_entry',
        ),
        migrations.AlterModelTable(
            name='availabilityschedule',
            table='rhea_a_schedule',
        ),
    ]
