# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhea', '0002_requirement_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='semester',
            field=models.PositiveSmallIntegerField(default=0, help_text="\n\t\t\tThe current semester for this student. This serves to exclude all possible candidates\n\t\t\twhich exceed the current semester by two units as to keep the least deviation possible\n\t\t\tin the study plan's progress.\n\t\t", verbose_name='current semester'),
        ),
    ]
