# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 06:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rhea', '0003_student_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course_schedule',
            field=models.OneToOneField(help_text="\n            This schedule is the current academic period's schedule for the instructor. This\n            specifies the courses the student should take and when should these be taken.\n            Since it is tied to the current academic period, this schedule has an expiry date.\n        ", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to='rhea.ScheduleFile', verbose_name='current course schedule'),
        ),
    ]
