# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhea', '0004_instructor_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='title',
            field=models.CharField(default='', help_text="\n\t\t\tBecause instructors have spent lots of time to earn that nice title of theirs,\n\t\t\tshouldn't we just provide them a way to showcase it?\n\t\t", max_length=16, verbose_name='title'),
        ),
    ]
