# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhea', '0005_auto_20160401_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='subjects',
            field=models.ManyToManyField(help_text="\n            This is a list of pointers to subjects in the academic program's requirements tree,\n            or course plan. The list points to current subjects only - candidates are calculated\n            on demand by the schedule generator.\n        ", related_name='students', related_query_name='students', to='rhea.Requirement', verbose_name='currently-coursing subjects'),
        ),
    ]
