# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 02:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rhea', '0009_auto_20160406_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='dependent',
            field=models.ForeignKey(help_text='\n\t        A pointer to a subject that requires the dependency - this stands for the forward side of\n\t        the relationship and allows for candidate estimation and progress tracking given a starting\n\t        set.\n\t    ', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='rhea.Subject', verbose_name='dependent'),
        ),
    ]
