# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhea', '0012_auto_20160427_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabilityschedule',
            name='entries',
            field=models.ManyToManyField(help_text='\n\t\t\tSchedules are sparse matrices of entries. In this case, this is a sparse matrix of\n\t\t\tavailability entries. Each availability entry represents a period of time per day\n\t\t\tin which the instructor may be assigned a course.\n\t\t', related_name='schedule', to='rhea.Availability', verbose_name='schedule entries'),
        ),
    ]
