# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 02:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rhea', '0013_auto_20160502_2315'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='is active')),
                ('expiry', models.DateTimeField(help_text="\n\t\t\tThe expiration date for this schedule. Schedules are valid per semester, but since we don't\n\t\t\treally know when is the semester scheduled to begin, we leave this to the staff to decide.\n\t\t", verbose_name='expiration date')),
                ('entries', models.ManyToManyField(help_text='\n\t\t\tThis indicates a course is to be taken by a student or instructed by an instructor. Since\n\t\t\tthis data is collected into the individual course object, we can relax the relationship and\n\t\t\tuse courses as the middle-man between students, instructors, subjects, and time slots.\n\t\t\tProgramming time is just so much fun!\n\t\t', related_name='schedule', to='rhea.Course', verbose_name='schedule entries')),
            ],
            options={
                'verbose_name': 'course schedule',
                'verbose_name_plural': 'course schedules',
            },
        ),
        migrations.AddField(
            model_name='instructor',
            name='schedule',
            field=models.OneToOneField(default=None, help_text="\n\t\t\tThis is the instructor's course schedule. This uses the same object type as the students'\n\t\t\tbecause they have the same things and serve the same purpose. The instructor's courses are,\n\t\t\thowever, not decided by them but by the system using our algorithm.\n\t\t", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructor', to='rhea.CourseSchedule', verbose_name='course schedule'),
        ),
        migrations.AddField(
            model_name='student',
            name='schedule',
            field=models.OneToOneField(default=None, help_text="\n\t\t\tThis is the student's course schedule. This uses the same object type as the instructors'\n\t\t\tbecause they have the same things and serve the same purpose. The student's courses are,\n\t\t\tunlike the instructors', chosen by themselves as part of the process, simplifying the\n\t\t\tendeavor.\n\t\t", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to='rhea.CourseSchedule', verbose_name='course schedule'),
        ),
    ]
