# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 17:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rhea', '0015_auto_20160503_0450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='subject',
            field=models.ForeignKey(help_text='\n\t\t\tThe subject of the course. The subject may only be offered once a day. Stacking\n\t\t\tcourses together counts only as one course and is thus valid. Stacking courses is\n\t\t\tunderstood to be vertically grouping two or more immediately consecutive courses into\n\t\t\ta single logical unit.\n\t\t', on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='rhea.Subject', verbose_name='course subject'),
        ),
    ]
